### ISSUE TITLE
[blog] Allow setting default post document via template

### ISSUE THREAD

**Issue by preaction** [preaction/Statocles#163]
Right now the default post content is hard-coded. We should make it into both a template and an attribute on the app. The template should be the default for the attribute.

We should make the following variables:

* user
* date (current date in YYYY-MM-DD)
* datetime (current date and time in YYYY-MM-DD HH:NN:SS)

**Comment by preaction** [comment]
@neilhwatson I think this is potentially the feature you want to set the default author. I would also totally accept a patch that allowed setting the default author from the config file (a blog app default author attribute).

**Comment by neilhwatson** [comment]
I would go further. What about an author bio blurb too. I'd love to fix this. Not sure if I can but, will look into it if I have time.

**Comment by preaction** [comment]
That'd be great. If you can't get to it, no worries. This one's on the v1 list (because it's related to #312, and could require some API breakage), and I'm likely going to start the v1 milestone sprint in the coming weeks.

And yeah, an author bio would be nice. There's a plan to use the Site object's `data` section to add things like social media links and other useful information. That information, if configured on the Site object, then gets displayed in the template (much like if you specify a disqus shortname, the disqus comments appear). I've opened a ticket about that (#400), and made it part of the v1 milestone because there'll be a lot of changes to the default set of themes to accommodate (which requires people to re-deploy their themes, and possibly re-apply any changes if they want to get the new stuff... maybe I should do template upgrades as diff/patch?)

**Comment by preaction** [comment]
Considering all the command-line options to set post content, and the ability to pipe content into STDIN, I'm not seeing a real need for this anymore. I also can't find any good way to develop it: It's not a proper template, it's completely optional, and it'd need to be able to be chosen on the command-line as well.

Closing this for now.
