### ISSUE TITLE
Constants from lexical variables potentially modified elsewhere are deprecated

### ISSUE THREAD

**Issue by eserte** [preaction/Statocles#190]
perl 5.21.x has a new warning "Constants from lexical variables potentially modified elsewhere are deprecated" which appears when running the test suite of Statocles. See http://www.cpantesters.org/cpan/report/ccc1cf40-8c71-11e4-b15b-1d0ce0bfc7aa for a sample test report (actually, this test report has also an unrelated test failure, but this is another issue).

**Comment by preaction** [comment]
Pull request for DPath merged. Waiting for a new release to depend on in Beam::Wire.
