### ISSUE TITLE
[static] Only works at the root of the site

### ISSUE THREAD

**Issue by preaction** [preaction/Statocles#227]
The static app only works when at the URL of "/", because it does not prefix the resulting Pages with the `url_root` attribute.

**Comment by vlet** [comment]
This can be trivially fixed. Did you plan some refactoring or just haven't enough time to fix yet?

**Comment by preaction** [comment]
Just haven't had enough time. Been trying to focus on the beta tickets, lots of doc-writing on the train ;)
