### ISSUE TITLE
Unicode in blog post titles

### ISSUE THREAD

**Issue by MagnusEnger** [preaction/Statocles#278]
Hi! I have been looking for a site generator written in Perl. Statocles looks very promising! :-) I did find a problem with Unicode in blog post titles, though. I run this:

```
$ statocles blog post Test æøå
```

And vim opens up to this:

```

---
tags: ~
title: Test Ã¦Ã¸Ã¥

---
Markdown content goes here.
```

This results in:

```
statocles blog post Test æøå
New post at: /home/magnus/Dropbox/libriotech.no/blog/2015/03/09/test-������/index.markdown
```

`statocles build` runs ok, but when I do `statocles daemon`, the title looks like "Test Ã¦Ã¸Ã¥" and the URL of the blog post is /blog/2015/03/09/test-Ã£Â¦Ã£Â¸Ã£Â¥ which gives a 404 when I click on it. Looks like there might be several layers of double encoding going on, or something? 

Personally, I'd prefer if the characters in the URL were reduced to ASCII, and the title displayed on the page was correct.

**Comment by preaction** [comment]
Arg! Unicode is hard! Though I meticulously tested utf-8 in content files, I didn't plan for unicode on the command-line! And in file names! And generally in everything else!

But, Mojolicious tries to solve this problem in URLs, so we'll probably follow them. And yes, gotta make sure to set UTF-8 on input, output, arguments, filenames, and etc...

The Ã is representative of the first high byte for UTF-8 being set, so the UTF-8 you've input is being misinterpreted as Latin-1. Probably just decoding `@ARGV` will fix a bunch of this.

And then we can have a flag to normalize the URL to ASCII. Not sure if that should be default or no though... Are all those scary issues with UTF-8 in URLs still open issues?

**Comment by MagnusEnger** [comment]
Yup, Unicode is hard. Sorry for bringing it up. ;-) I dunno about the state of UTF-8 in URLs, but i prefer to err on the side of caution...

**Comment by preaction** [comment]
I've started a new branch, utf8-everywhere, in an attempt to fix this problem. Reproducing this seems to simply involve having a locale that isn't set to UTF-8 and trying to use a non-ASCII character, which makes sense. What doesn't make sense is that decoding doesn't seem to work. I think I'm going to have to change my terminal to be non-UTF-8 to debug further.

**Comment by preaction** [comment]
I think the problem I'm having is that OSX requires filenames to be some kind of UTF-8. Reading Github Pages documentation says they require UTF-8 output, but I can see needing to specify another file encoding.

So right now the plan seems to be:

1) Decode input from the current locale
    * STDIN
    * `@ARGV`
2) Output to the terminal is in the current locale
    * STDOUT
    * STDERR
3) Output to files must be UTF-8
    * Except binary files must be raw bytes
    * Allow setting the file output encoding in a Store, later
4) On OS X, encode file paths to UTF-8
    * Do other things like this as needed
