### ISSUE TITLE
Test performance of sites with 10,000 documents

### ISSUE THREAD

**Issue by preaction** [preaction/Statocles#317]
We should see how our performance degrades with very very large sites. This is important as it may require some API changes like:

* Lazy-loading from the daemon
* Dependency generation
* Document cache expiration (#217)

This is such a large change I might be able to punt on this until version 2...

**Comment by preaction** [comment]
#377 should help speed up performance a bit, but we should still do some real performance testing.

**Comment by neilhwatson** [comment]
I do notice that builds take longer that I would expect:

    neil@ettin ~/src/www.watson-wilson.ca $ time statocles build

    real    0m22.380s
    user    0m16.540s
    sys     0m0.108s

**Comment by preaction** [comment]
I'm finding the biggest bottlenecks for the Statocles website are Text::Markdown above all else, and Pod::Weaver next. For an image-heavy website, IndiePalate, the biggest bottleneck is Statocles::Store::write_file, which is to be expected, and should be addressed.

I can get some speedup from some caching in Statocles::Page (committed as 1ed4b60), since the LinkCheck plugin does a second render, and we can likely get a bit fancier with caching in there in anticipation of a dependency event flow.

Using [Text::Markdown::Hoedown](https://metacpan.org/pod/Text::Markdown::Hoedown) gets me some more speedup, but its API is not object-oriented. I'm going to submit a patch, otherwise I'll make a shim or something.

**Comment by preaction** [comment]
I am also likely not caching the Mojo::Template objects in Statocles::Template. They should only need to be parsed once. We are likely doing it every time.

**Comment by preaction** [comment]
Forgot to mention: The preliminary performance enhancements went out with v0.060, so you should get a bit of speedup if you upgrade.

Let me know if there are any problems. I'm now caching pretty aggressively, and I'm worried there are edge cases where the cache should be invalidated but isn't.

**Comment by neilhwatson** [comment]
Great improvement

    neil@ettin ~/src/www.watson-wilson.ca $ time statocles build

    real    0m5.671s
    user    0m5.620s
    sys     0m0.048s

**Comment by kentfredric** [comment]
would it be possible to assume a user understands what they're changing, then do
```bash
$ statocles build ./PATH/TO/CHANGED/CONTENT
```

And have it only regenerate the built copy of that asset and its dependent assets?

If you could do that, then as long as you're using git, you could simply compute the changed content based on the dirty state, or the diff stats between the last built commit, essentially deferring your cache mechanism to git.

**Comment by preaction** [comment]
The problem is knowing the dependency graph: Templates, plugins, and event handlers can add dependencies that could be hard to detect, and likely harder to narrow down enough to make it worth it for performance. 

For example, if my layout contains a list of the last 5 blog entries (gotten via `$site->app( "blog" )->recent_posts`), and then I add a new blog entry, every single page needs to be regenerated, but since that list is added to the template using a template directive, it could be anything at all.

So, when things add dependencies, they must have a way to declare those dependencies so they can be monitored. This will likely require some methods to manage dependencies on the Page role, and for template-based dependencies like the blog entry list, some template directives. The case of adding/removing pages is the annoying case...

(The template version of things could even make adding content better, doing something like:

```
% embed $site->app("blog")->recent_posts( limit => 5 ) => begin
<h2><%= embedded_page->title %></h2>
% end
```

Then after `recent_posts` returned the pages, `embed` would add them to this page's dependencies, or something. Not sure that exact example is better, needs some refinement...)

Deferring to git might be possible, but git isn't a requirement for Statocles, and I'm not sure I want to make it one (though why anyone would choose/do differently is beyond me). For the most part, I was considering the daemon: While the daemon is running, we have a cache, when it stops, the cache is dead. Though, we could serialize that cached state, then on the next build, compare it to any data we can to see what changed (git status, modified times), and achieve the same result without a persistent process.

**Comment by preaction** [comment]
I think we've done what we can here for now. I've made another ticket for the dependency graphs (#493), and we'll revisit performance again after v1.000
