### ISSUE TITLE
[plain] Command to create new plain page

### ISSUE THREAD

**Issue by preaction** [preaction/Statocles#338]
Just like the blog app, there should be a command to create a plain page. We should give it a URL path and open up the editor.

**Comment by cmdcolin** [comment]
Ideally it could also have a "help" page? The docs indicate the "apps" can have a help page like  "statocles blog help"  does but "statocles page help" just has an error currently


    Can't locate object method "command" via package "Statocles::App::Plain" at ~/perl5/lib/perl5/Statocles/Command.pm

**Comment by preaction** [comment]
Yes, if there's going to be a command-line utility for the app, there will need to be a corresponding "help" command to document it.

There's also #51 as well, a generic help command (really, that's to get to the guides, the Statocles::Help::* stuff).

But it looks like there's another bug here, too: Apps that have no commands give a very strange error message. So, the Perldoc app and Static app will both have the same problem, and there is yet no plans to give them commands. The Statocles::Command class will have to check for the `command` method before doing something. (Ticket created as #379).

Though, it might be interesting to give every app a "list/ls" command to list all the pages they would generate. And a "show" command to show the content for a page... Maybe there's something to that... That probably ties in to #315 and #216 then. The "edit/new" command may even be generic enough to work for any document-based app (so, excepting the Static and Perldoc apps). Then, there'd be less reason to check for a `command` method, as every app has a default `command` method.
