### ISSUE TITLE
Installation test failure

### ISSUE THREAD

**Issue by kylesheely** [preaction/Statocles#349]
Output:

```
# Use of uninitialized value $1 in lc at /usr2/local/perlbrew/perls/perl-5.16.3/lib/site_perl/5.16.3/Pod/Simple/Search.pm line 353.
    # Looks like you failed 1 test of 27.
t/app/perldoc/pages.t ......... 1/? 
#   Failed test 'without Pod::Weaver'
#   at t/app/perldoc/pages.t line 185.
    
    #   Failed test 'no warnings!'
    #   at t/app/perldoc/pages.t line 254.
```

**Comment by preaction** [comment]
Some notes: This happened even on the most recent Pod::Simple

**Comment by preaction** [comment]
Somehow, `warnings` is being enabled globally, which is quite a problem (and this test failure is why the `-w` switch shouldn't be used). Some prereq is enabling warnings for everything, or somehow `PERL5OPT` or something has been set with `-w` (which I doubt highly).

**Comment by preaction** [comment]
Looks like this was fixed in theory/pod-simple@37e1a25. We just need to depend on the new version after it's released to CPAN.

**Comment by preaction** [comment]
I left a message on the RT ticket: https://rt.cpan.org/Ticket/Display.html?id=103439. If this doesn't get a new stable Pod::Simple shipped, I'll have to find some way to ignore just that warning...

**Comment by preaction** [comment]
3.31 is finally released!
