### ISSUE TITLE
Rename Plain app to something better

### ISSUE THREAD

**Issue by preaction** [preaction/Statocles#380]
"Plain" means less than "Page". It's an app for pages.

We could also combine "Plain" and "Static" into the "Page" app.

**Comment by preaction** [comment]
Or we could just call it Static

**Comment by AdUser** [comment]
Maybe call it "Simple"? And add some sort of autoindex from #352, if index.markdown file missing.

**Comment by preaction** [comment]
I think I should do some research and see what other things call it. I was thinking "Page" because that's what Wordpress would call it, but it doesn't make much sense in this context. "Static" or "Simple" sound more accurate.

Ah, yes, right, with this ticket, #352 will have to be moved into the resulting combined app. Which then is the added value for the app class itself, since the basic functionality of pages/files anywhere is going to be moved into the base Statocles::App class (#343)

**Comment by preaction** [comment]
I like "Simple", but how about "Basic"? I like the "Base" connotation, that this is a "Base" app functionality, especially considering #343 making every app do at least what this app will do
