### ISSUE TITLE
Can't locate object method "new" via package "Statocles::Template"

### ISSUE THREAD

**Issue by neilhwatson** [preaction/Statocles#403]
statocles create www.example.com

With all default answers produces:

Can't locate object method "new" via package "Statocles::Template" (perhaps you forgot to load "Statocles::Template"?) at /home/neil/perl5/lib/perl5/Statocles/Command.pm line 292, <STDIN> line 4.

**Comment by preaction** [comment]
Confirmed. This is what I get for being overzealous with the `use` lines in my tests. Fix incoming.
