### ISSUE TITLE
.058 failes to install

### ISSUE THREAD

**Issue by neilhwatson** [preaction/Statocles#404]
Install log below. Host is Debian 64bit 'testing'. Problem appears to be with HTML::Lint::Pluggable

      cpanm (App::cpanminus) 1.7014 on perl 5.020002 built for x86_64-linux-gnu-thread-multi
      Work directory is /home/neil/.cpanm/work/1447334463.20652
      You have make /usr/bin/make
      You have LWP 6.13
      You have /bin/tar: tar (GNU tar) 1.28
      Copyright (C) 2014 Free Software Foundation, Inc.
      License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.

      Written by John Gilmore and Jay Fenlason.
      You have /usr/bin/unzip
      Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (6.98)
      Checking if you have ExtUtils::Install 1.46 ... Yes (1.67)
      Searching install on cpanmetadb ...
      install is up to date. (0.01)
      Searching Statocles on cpanmetadb ...
      --> Working on Statocles
      Fetching http://www.cpan.org/authors/id/P/PR/PREACTION/Statocles-0.058.tar.gz
      -> OK
      Unpacking Statocles-0.058.tar.gz
      Entering Statocles-0.058
      Checking configure dependencies from META.yml
      Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.98)
      Checking if you have File::ShareDir::Install 0.06 ... Yes (0.10)
      Configuring Statocles-0.058
      Running Makefile.PL
      Checking if your kit is complete...
      Looks good
      Generating a Unix-style Makefile
      Writing Makefile for Statocles
      Writing MYMETA.yml and MYMETA.json
      -> OK
      Checking dependencies from MYMETA.json ...
      Checking if you have IO::Handle 0 ... Yes (1.35)
      Checking if you have Path::Tiny 0.072 ... Yes (0.072)
      Checking if you have Beam::Wire 1.014 ... Yes (1.014)
      Checking if you have File::Spec 0 ... Yes (3.48_01)
      Checking if you have Git::Repository 0 ... Yes (1.315)
      Checking if you have IPC::Open3 0 ... Yes (1.16)
      Checking if you have Text::Markdown 0 ... Yes (1.000031)
      Checking if you have Dir::Self 0 ... Yes (0.11)
      Checking if you have Moo 2.000001 ... Yes (2.000002)
      Checking if you have warnings 0 ... Yes (1.23)
      Checking if you have Test::Deep 0 ... Yes (0.119)
      Checking if you have Test::Differences 0 ... Yes (0.63)
      Checking if you have Time::Piece 0 ... Yes (1.27)
      Checking if you have Pod::Simple 3.31 ... Yes (3.31)
      Checking if you have Capture::Tiny 0 ... Yes (0.30)
      Checking if you have Test::Lib 0 ... Yes (0.002)
      Checking if you have Test::More 1.001005 ... Yes (1.001014)
      Checking if you have Import::Base 0.012 ... Yes (0.014)
      Checking if you have Pod::Usage::Return 0 ... Yes (0.003)
      Checking if you have strict 0 ... Yes (1.08)
      Checking if you have Beam::Emitter 0.007 ... Yes (1.000)
      Checking if you have File::Share 0 ... Yes (0.25)
      Checking if you have Test::Exception 0 ... Yes (0.40)
      Checking if you have Mojolicious 6.0 ... Yes (6.15)
      Checking if you have Type::Tiny 0 ... Yes (1.000005)
      Checking if you have Types::Path::Tiny 0 ... Yes (0.005)
      Checking if you have Storable 0 ... Yes (2.49_01)
      Checking if you have Encode 0 ... Yes (2.60)
      Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.98)
      Checking if you have YAML 0 ... Yes (1.13)
      Building and testing Statocles-0.058
      cp share/theme/default/perldoc/source.html.ep blib/lib/auto/share/dist/Statocles/theme/default/perldoc/source.html.ep
      cp share/theme/bootstrap/css/statocles-bootstrap.css blib/lib/auto/share/dist/Statocles/theme/bootstrap/css/statocles-bootstrap.css
      cp share/create/site.yml blib/lib/auto/share/dist/Statocles/create/site.yml
      cp share/create/blog/post.markdown blib/lib/auto/share/dist/Statocles/create/blog/post.markdown
      cp share/theme/default/blog/index.atom.ep blib/lib/auto/share/dist/Statocles/theme/default/blog/index.atom.ep
      cp share/theme/bootstrap/site/head_after.html.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/head_after.html.ep
      cp share/theme/bootstrap/site/header_after.html.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/header_after.html.ep
      cp share/theme/bootstrap/site/sidebar_before.html.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/sidebar_before.html.ep
      cp share/theme/bootstrap/site/navbar_extra.html.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/navbar_extra.html.ep
      cp share/theme/default/perldoc/pod.html.ep blib/lib/auto/share/dist/Statocles/theme/default/perldoc/pod.html.ep
      cp share/theme/default/css/skeleton.css blib/lib/auto/share/dist/Statocles/theme/default/css/skeleton.css
      cp share/theme/default/site/robots.txt.ep blib/lib/auto/share/dist/Statocles/theme/default/site/robots.txt.ep
      cp share/theme/default/css/normalize.css blib/lib/auto/share/dist/Statocles/theme/default/css/normalize.css
      cp share/theme/bootstrap/blog/index.html.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/blog/index.html.ep
      cp share/theme/default/site/layout.html.ep blib/lib/auto/share/dist/Statocles/theme/default/site/layout.html.ep
      cp share/theme/bootstrap/blog/index.rss.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/blog/index.rss.ep
      cp share/theme/default/site/navbar_extra.html.ep blib/lib/auto/share/dist/Statocles/theme/default/site/navbar_extra.html.ep
      cp share/theme/bootstrap/site/style.html blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/style.html
      cp share/theme/default/site/style.html blib/lib/auto/share/dist/Statocles/theme/default/site/style.html
      cp share/theme/bootstrap/site/layout.html.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/layout.html.ep
      cp share/theme/default/css/statocles-default.css blib/lib/auto/share/dist/Statocles/theme/default/css/statocles-default.css
      cp share/theme/bootstrap/blog/post.html.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/blog/post.html.ep
      cp share/theme/default/blog/index.html.ep blib/lib/auto/share/dist/Statocles/theme/default/blog/index.html.ep
      cp share/theme/bootstrap/site/sitemap.xml.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/sitemap.xml.ep
      cp share/theme/bootstrap/perldoc/pod.html.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/perldoc/pod.html.ep
      cp share/zsh/_statocles blib/lib/auto/share/dist/Statocles/zsh/_statocles
      cp share/theme/default/blog/post.html.ep blib/lib/auto/share/dist/Statocles/theme/default/blog/post.html.ep
      cp share/theme/bootstrap/site/footer.html.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/footer.html.ep
      cp share/create/script.yml blib/lib/auto/share/dist/Statocles/create/script.yml
      cp share/theme/default/blog/index.rss.ep blib/lib/auto/share/dist/Statocles/theme/default/blog/index.rss.ep
      cp share/theme/default/site/head_after.html.ep blib/lib/auto/share/dist/Statocles/theme/default/site/head_after.html.ep
      cp share/theme/default/site/header_after.html.ep blib/lib/auto/share/dist/Statocles/theme/default/site/header_after.html.ep
      cp share/theme/bootstrap/perldoc/source.html.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/perldoc/source.html.ep
      cp share/create/page/index.markdown blib/lib/auto/share/dist/Statocles/create/page/index.markdown
      cp share/theme/bootstrap/site/robots.txt.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/robots.txt.ep
      cp share/theme/default/site/sidebar_before.html.ep blib/lib/auto/share/dist/Statocles/theme/default/site/sidebar_before.html.ep
      cp share/theme/default/site/footer.html.ep blib/lib/auto/share/dist/Statocles/theme/default/site/footer.html.ep
      cp share/theme/bootstrap/blog/index.atom.ep blib/lib/auto/share/dist/Statocles/theme/bootstrap/blog/index.atom.ep
      cp share/theme/default/site/sitemap.xml.ep blib/lib/auto/share/dist/Statocles/theme/default/site/sitemap.xml.ep
      cp lib/Statocles/Help/Deploy.pod blib/lib/Statocles/Help/Deploy.pod
      cp lib/Statocles/App/Static.pm blib/lib/Statocles/App/Static.pm
      cp lib/Statocles/Theme.pm blib/lib/Statocles/Theme.pm
      cp lib/Statocles/Help/Upgrading.pod blib/lib/Statocles/Help/Upgrading.pod
      cp lib/Statocles/App/Blog.pm blib/lib/Statocles/App/Blog.pm
      cp lib/Statocles/Help/Policy.pod blib/lib/Statocles/Help/Policy.pod
      cp lib/Statocles.pm blib/lib/Statocles.pm
      cp lib/Statocles/Test.pm blib/lib/Statocles/Test.pm
      cp lib/Statocles/Help/Content.pod blib/lib/Statocles/Help/Content.pod
      cp lib/Statocles/Deploy/Git.pm blib/lib/Statocles/Deploy/Git.pm
      cp lib/Statocles/Document.pm blib/lib/Statocles/Document.pm
      cp lib/Statocles/Command.pm blib/lib/Statocles/Command.pm
      cp lib/Statocles/Page/Plain.pm blib/lib/Statocles/Page/Plain.pm
      cp lib/Statocles/Deploy/File.pm blib/lib/Statocles/Deploy/File.pm
      cp lib/Statocles/Page/List.pm blib/lib/Statocles/Page/List.pm
      cp lib/Statocles/Page/File.pm blib/lib/Statocles/Page/File.pm
      cp lib/Statocles/Plugin/HTMLLint.pm blib/lib/Statocles/Plugin/HTMLLint.pm
      cp lib/Statocles/Help/Error.pod blib/lib/Statocles/Help/Error.pod
      cp lib/Statocles/Page/ListItem.pm blib/lib/Statocles/Page/ListItem.pm
      cp lib/Statocles/Help.pod blib/lib/Statocles/Help.pod
      cp lib/Statocles/App/Plain.pm blib/lib/Statocles/App/Plain.pm
      cp lib/Statocles/Page/Document.pm blib/lib/Statocles/Page/Document.pm
      cp lib/Statocles/Help/Develop.pod blib/lib/Statocles/Help/Develop.pod
      cp lib/Statocles/Site.pm blib/lib/Statocles/Site.pm
      cp lib/Statocles/App/Role/Store.pm blib/lib/Statocles/App/Role/Store.pm
      cp lib/Statocles/Event.pm blib/lib/Statocles/Event.pm
      cp lib/Statocles/Base.pm blib/lib/Statocles/Base.pm
      cp lib/Statocles/Help/Theme.pod blib/lib/Statocles/Help/Theme.pod
      cp lib/Statocles/Util.pm blib/lib/Statocles/Util.pm
      cp lib/Statocles/Store/File.pm blib/lib/Statocles/Store/File.pm
      cp lib/Statocles/Page.pm blib/lib/Statocles/Page.pm
      cp lib/Statocles/Deploy.pm blib/lib/Statocles/Deploy.pm
      cp lib/Statocles/Store.pm blib/lib/Statocles/Store.pm
      cp lib/Statocles/Help/Config.pod blib/lib/Statocles/Help/Config.pod
      cp lib/Statocles/Help/Setup.pod blib/lib/Statocles/Help/Setup.pod
      cp lib/Statocles/Plugin/LinkCheck.pm blib/lib/Statocles/Plugin/LinkCheck.pm
      cp lib/Statocles/App/Basic.pm blib/lib/Statocles/App/Basic.pm
      cp lib/Statocles/Link.pm blib/lib/Statocles/Link.pm
      cp lib/Statocles/Types.pm blib/lib/Statocles/Types.pm
      cp lib/Statocles/App/Perldoc.pm blib/lib/Statocles/App/Perldoc.pm
      cp lib/Statocles/Template.pm blib/lib/Statocles/Template.pm
      cp lib/Statocles/App.pm blib/lib/Statocles/App.pm
      cp bin/statocles blib/script/statocles
      /usr/bin/perl -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/statocles
      Manifying blib/man1/statocles.1p
      Manifying blib/man3/Statocles.3pm
      Manifying blib/man3/Statocles::App.3pm
      Manifying blib/man3/Statocles::App::Basic.3pm
      Manifying blib/man3/Statocles::App::Blog.3pm
      Manifying blib/man3/Statocles::App::Perldoc.3pm
      Manifying blib/man3/Statocles::App::Plain.3pm
      Manifying blib/man3/Statocles::App::Role::Store.3pm
      Manifying blib/man3/Statocles::App::Static.3pm
      Manifying blib/man3/Statocles::Base.3pm
      Manifying blib/man3/Statocles::Command.3pm
      Manifying blib/man3/Statocles::Deploy.3pm
      Manifying blib/man3/Statocles::Deploy::File.3pm
      Manifying blib/man3/Statocles::Deploy::Git.3pm
      Manifying blib/man3/Statocles::Document.3pm
      Manifying blib/man3/Statocles::Event.3pm
      Manifying blib/man3/Statocles::Help.3pm
      Manifying blib/man3/Statocles::Help::Config.3pm
      Manifying blib/man3/Statocles::Help::Content.3pm
      Manifying blib/man3/Statocles::Help::Deploy.3pm
      Manifying blib/man3/Statocles::Help::Develop.3pm
      Manifying blib/man3/Statocles::Help::Error.3pm
      Manifying blib/man3/Statocles::Help::Policy.3pm
      Manifying blib/man3/Statocles::Help::Setup.3pm
      Manifying blib/man3/Statocles::Help::Theme.3pm
      Manifying blib/man3/Statocles::Help::Upgrading.3pm
      Manifying blib/man3/Statocles::Link.3pm
      Manifying blib/man3/Statocles::Page.3pm
      Manifying blib/man3/Statocles::Page::Document.3pm
      Manifying blib/man3/Statocles::Page::File.3pm
      Manifying blib/man3/Statocles::Page::List.3pm
      Manifying blib/man3/Statocles::Page::ListItem.3pm
      Manifying blib/man3/Statocles::Page::Plain.3pm
      Manifying blib/man3/Statocles::Plugin::HTMLLint.3pm
      Manifying blib/man3/Statocles::Plugin::LinkCheck.3pm
      Manifying blib/man3/Statocles::Site.3pm
      Manifying blib/man3/Statocles::Store.3pm
      Manifying blib/man3/Statocles::Store::File.3pm
      Manifying blib/man3/Statocles::Template.3pm
      Manifying blib/man3/Statocles::Test.3pm
      Manifying blib/man3/Statocles::Theme.3pm
      Manifying blib/man3/Statocles::Types.3pm
      Manifying blib/man3/Statocles::Util.3pm
      Skip blib/lib/auto/share/dist/Statocles/theme/default/blog/index.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/navbar_extra.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/site/style.html (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/css/statocles-bootstrap.css (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/blog/index.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/site/navbar_extra.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/css/normalize.css (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/css/statocles-default.css (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/site/layout.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/perldoc/pod.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/site/robots.txt.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/blog/index.atom.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/layout.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/style.html (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/head_after.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/perldoc/source.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/create/site.yml (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/blog/post.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/blog/index.rss.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/sidebar_before.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/css/skeleton.css (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/create/blog/post.markdown (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/header_after.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/perldoc/pod.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/blog/index.atom.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/site/sidebar_before.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/zsh/_statocles (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/perldoc/source.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/site/head_after.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/create/script.yml (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/site/footer.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/blog/index.rss.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/footer.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/create/page/index.markdown (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/site/sitemap.xml.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/site/header_after.html.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/sitemap.xml.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/bootstrap/site/robots.txt.ep (unchanged)
      Skip blib/lib/auto/share/dist/Statocles/theme/default/blog/post.html.ep (unchanged)
      PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t t/app/*.t t/app/basic/*.t t/app/blog/*.t t/app/perldoc/*.t t/app/role/*.t t/bin/*.t t/command/*.t t/deploy/*.t t/page/*.t t/plugin/*.t t/site/*.t t/store/*.t t/template/*.t t/theme/*.t

        #   Failed test 'Statocles/Plugin/HTMLLint.pm loaded ok'
        #   at t/00-compile.t line 69.
        #          got: '512'
        #     expected: '0'
      Error loading Statocles::Plugin::HTMLLint. To use this plugin, install HTML::Lint::Pluggable at /home/neil/.cpanm/work/1447334463.20652/Statocles-0.058/blib/lib/Statocles/Plugin/HTMLLint.pm line 6.
      BEGIN failed--compilation aborted at /home/neil/.cpanm/work/1447334463.20652/Statocles-0.058/blib/lib/Statocles/Plugin/HTMLLint.pm line 8.
      Compilation failed in require at -e line 1.
        # Looks like you failed 1 test of 32.
      t/00-compile.t ................ 
      Dubious, test returned 1 (wstat 256, 0x100)
      Failed 1/32 subtests 
         (less 1 skipped subtest: 30 okay)
        # 
        # Versions for all modules listed in MYMETA.json (including optional ones):
        # 
        # === Configure Requires ===
        # 
        #     Module                  Want Have
        #     ----------------------- ---- ----
        #     ExtUtils::MakeMaker      any 6.98
        #     File::ShareDir::Install 0.06 0.10
        # 
        # === Build Requires ===
        # 
        #     Module              Want Have
        #     ------------------- ---- ----
        #     ExtUtils::MakeMaker  any 6.98
        # 
        # === Test Requires ===
        # 
        #     Module                  Want     Have
        #     ------------------- -------- --------
        #     Capture::Tiny            any     0.30
        #     Dir::Self                any     0.11
        #     ExtUtils::MakeMaker      any     6.98
        #     File::Spec               any  3.48_01
        #     IO::Handle               any     1.35
        #     IPC::Open3               any     1.16
        #     Storable                 any  2.49_01
        #     Test::Deep               any    0.119
        #     Test::Differences        any     0.63
        #     Test::Exception          any     0.40
        #     Test::Lib                any    0.002
        #     Test::More          1.001005 1.001014
        # 
        # === Test Recommends ===
        # 
        #     Module         Want     Have
        #     ---------- -------- --------
        #     CPAN::Meta 2.120900 2.150005
        # 
        # === Runtime Requires ===
        # 
        #     Module                 Want     Have
        #     ------------------ -------- --------
        #     Beam::Emitter         0.007    1.000
        #     Beam::Wire            1.014    1.014
        #     Encode                  any     2.60
        #     File::Share             any     0.25
        #     Git::Repository         any    1.315
        #     Import::Base          0.012    0.014
        #     Mojolicious             6.0     6.15
        #     Moo                2.000001 2.000002
        #     Path::Tiny            0.072    0.072
        #     Pod::Simple            3.31     3.31
        #     Pod::Usage::Return      any    0.003
        #     Text::Markdown          any 1.000031
        #     Time::Piece             any     1.27
        #     Type::Tiny              any 1.000005
        #     Types::Path::Tiny       any    0.005
        #     YAML                    any     1.13
        #     strict                  any     1.08
        #     warnings                any     1.23
        # 
        # === Runtime Recommends ===
        # 
        #     Module                Want    Have
        #     --------------------- ---- -------
        #     HTML::Lint::Pluggable 0.06 missing
        #     PPI                    any   1.220
        #     Pod::Elemental         any missing
        #     Pod::Weaver            any missing
        # 
      t/00-report-prereqs.t ......... ok
                          # Before test: STDIN is interactive
                          # After test: STDIN is interactive
                          # Before test: STDIN is interactive
                          # After test: STDIN is interactive
      t/app/basic/command.t ......... ok
      t/app/basic/constructor.t ..... ok
      t/app/basic/pages.t ........... ok
                          # Before test: STDIN is interactive
                          # After test: STDIN is interactive
                          # Before test: STDIN is interactive
                          # After test: STDIN is interactive
      t/app/blog/command.t .......... ok
      t/app/blog/constructor.t ...... ok
          # Current LC_TIME locale: en_CA.UTF-8
          # Could not set locale to ru_RU. Still 
      t/app/blog/pages.t ............ ok
      t/app/blog/recent_posts.t ..... ok
      t/app/events.t ................ ok
      t/app/perldoc/constructor.t ... ok
      t/app/perldoc/pages.t ......... ok
      t/app/role/store.t ............ ok
      t/app/url.t ................... ok
      t/bin/statocles.t ............. ok
      t/command/apps.t .............. ok
              # Git version: 2.006001
      t/command/build_and_deploy.t .. ok
      t/command/bundle.t ............ ok
          # Git version: 2.006001
      t/command/create.t ............ ok
      t/command/daemon.t ............ ok
      t/command/error.t ............. ok
      t/command/help_and_version.t .. ok
      t/command/mojo_app.t .......... ok
      t/deploy/file.t ............... ok
        # Git version: 2.006001
      t/deploy/git.t ................ ok
      t/deprecated.t ................ ok
      t/link.t ...................... ok
      t/page/basename.t ............. ok
      t/page/document.t ............. ok
      t/page/file.t ................. ok
      t/page/links.t ................ ok
      t/page/list.t ................. ok
      t/page/list_item.t ............ ok
      t/page/plain.t ................ ok
      t/page/type.t ................. ok
      t/plugin/html_lint.t .......... skipped: HTML::Lint::Pluggable needed
      t/plugin/link_check.t ......... ok
      t/site/build_and_deploy.t ..... ok
      t/site/constructor.t .......... ok
      t/site/data.t ................. ok
      t/site/events.t ............... ok
      t/site/index.t ................ ok
      t/site/nav.t .................. ok
      t/site/sitemap_and_robots.t ... ok
      t/site/url.t .................. ok
      t/site/warnings.t ............. ok
      t/store/constructor.t ......... ok
      t/store/document.t ............ ok
      t/store/file.t ................ ok
      t/template/basic.t ............ ok
      t/template/include.t .......... ok
      t/template/markdown.t ......... ok
      t/theme/check.t ............... ok
      t/theme/pages.t ............... ok
      t/theme/template.t ............ ok
      t/types.t ..................... ok
      t/util.t ...................... ok

      Test Summary Report
      -------------------
      t/00-compile.t              (Wstat: 256 Tests: 32 Failed: 1)
        Failed test:  23
        Non-zero exit status: 1
      Files=57, Tests=307, 43 wallclock secs ( 0.36 usr  0.03 sys + 39.59 cusr  1.92 csys = 41.90 CPU)
      Result: FAIL
      Failed 1/57 test programs. 1/307 subtests failed.
      Makefile:1140: recipe for target 'test_dynamic' failed
      make: *** [test_dynamic] Error 255
      -> FAIL Installing Statocles failed. See /home/neil/.cpanm/work/1447334463.20652/build.log for details. Retry with --force to force install it.

**Comment by preaction** [comment]
Sorry about that, v0.059 is on its way to CPAN now. Thanks.
