### ISSUE TITLE
[plugin] Syntax highlighting plugin

### ISSUE THREAD

**Issue by preaction** [preaction/Statocles#407]
After #406, we need a plugin to be able to add syntax highlighting to our content (see #405).

Preferably, we'd be able to do:

```
```perl
use strict;
use warnings;
# ...
\```
```

Just like Github-Flavored Markdown.

Otherwise, it would be acceptable to do:

```
% begin highlight perl =>
use strict;
use warnings;
# ...
% end
```

Like Mojolicious templates allow.

**Comment by kentfredric** [comment]
+1, the lack of something nice here is the biggest reason I'm avoiding most the commercial blogging platforms like Blogger, Medium, Tumblr, etc, because they are all painfully atrocious when it comes to embedding code.

Even Githubs Jekyll based Github Pages stuff is very much ugly here, requiring some horrible nasty template engine syntax to get code sections working.

I mean really: https://truongtx.me/2012/12/28/jekyll-bootstrap-syntax-highlighting/ 

![no](http://i.giphy.com/12XMGIWtrHBl5e.gif)

**Comment by preaction** [comment]
It looks like the easy/popular options are [Syntax::Highlight::Engine::Kate](https://metacpan.org/pod/Syntax::Highlight::Engine::Kate) and [Text::VimColor](https://metacpan.org/pod/Text::VimColor). The Kate one at least seems like such an easy dependency to add that I could just add it to the base package for a quick win now. Then I don't necessarily have to wait for #406 (but nothing's really blocking that except my own anxiety about how to manage plugins).

The trouble with extending `Text::Markdown` to add the Github-Flavored triple backtick is that it locks us into the one Markdown processor. I'm not yet ready to close that door (indeed I'm no longer sure it can/should be closed, [due to performance concerns](https://github.com/preaction/Statocles/issues/317#issuecomment-158613304)), so it'd be better to provide a plugin to do it.

The standard Mojo::Template `begin`/`end` seems to work, so it'd probably look like:

```
% highlight perl => begin
sub foo { ... }
% end
```

I should also test if including a file works as well, like:

```
% highlight perl => include "script.pl"
```

That'd be awesome, and it works for the `markdown` helper, so I've got no reason to believe it won't work here.

The Kate plugin only provides HTML, we'll need to provide a default stylesheet (or a few) and document how to modify it. Forwarding users onto the Syntax::Highlight::Engine::Kate docs may suffice, but a quick overview would be helpful.

For the future, we could provide additional features like a simple template to build a nice panel/frame for the code, a "Raw" button to show an unhighlighted text area or a new window or something, and I know I've seen other platforms provide other features (like [these plugins for Prism](http://prismjs.com/#plugins)). Auto-linking would be awesome for the Perldoc app, and if it could be configured to link examples from blog posts to docs on that same site, that'd be really nice.

If the future requires inline options to the highlighter, we could allow a hashref as the first argument:

```
% highlight { type => 'perl', indent => 4 } => begin
sub foo { ... }
% end
```

**Comment by preaction** [comment]
I was wrong, the Syntax::Highlight::Engine::Kate module does not provide HTML at all, we have to define what HTML it provides. Right now I'm trying to map the Kate bits onto the [classes that highlight.js uses](http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html) so we can use their stylesheets, except highlight.js has a bunch more things it detects, and the Syntax::Highlight::Engine::Kate module doesn't explain what things are which. Checking [the Kate syntax highlighting docs](https://docs.kde.org/stable5/en/applications/katepart/highlight.html) shows that newer versions of Kate support more things as well, so now I'm questioning using the Syntax::Highlight::Engine::Kate module at all...

**Comment by preaction** [comment]
And now this is starting to annoy me: Kate treats quotation marks as operators, but highlightjs treats them as part of the string. So there's no real good way to combine the theme files from highlightjs with the syntax hints of Kate and get the same output. There's also no way to distinguish the quoting operators from any other operator.

I'm getting to the point where I'm considering offering multiple different highlighter plugins, because I really, really do not want to start a collection of highlighter themes...

I suppose, in the grand scheme of things, I don't have to do anything for a JS highlighter, because people can just add that. And in the future, we can have things like `Statocles::Plugin::Highlight::Prism` and `Statocles::Plugin::Highlight::HighlightJS` that are drop-in replacements for this one...
