### ISSUE TITLE
Generated initial blog has 404 link

### ISSUE THREAD

**Issue by kentfredric** [preaction/Statocles#419]
On this page:

```html
<article>
  <header>
   <h1><a href="/blog/2015/12/29/first-post/">First Post</a></h1>
   <p class="tags">Tags:</p>
   <aside><p><time datetime="2015-12-29">Posted on 2015-12-29</time></p></aside>
  </header>
  <h1>Welcome To Your Blog</h1>
  <p>This is your first post. To edit this post, open up /blog/2015/12/29/first-post/index.markdown in your text editor.</p>
  <p><a href="http://preaction.me/statocles/pod/Statocles/Help/Content.html">Check the documentation for how to write Statocles content</a></p>
</article>
```

That trailing `<a href=` 404s'. 

Seems it needs the `.html` part stripped.

**Comment by preaction** [comment]
Argh. Yes. I removed the `.html` from the Perldoc app a while back... A full test of the content the site creator generates and the external link-checker (#374) would be good to make sure this doesn't happen again (as long as a `statocles deploy` doesn't write any warnings, provided the external link checker is working, it should be good).
