### ISSUE TITLE
missing dependency for Statocles::Plugin::Highlight

### ISSUE THREAD

**Issue by AdUser** [preaction/Statocles#426]
When installing with cpanm, i've got the following:

```
t/command/create.t ............ ok
t/command/daemon.t ............ ok
Error loading Statocles::Plugin::Highlight. To use this plugin, install Syntax::Highlight::Engine::Kate at /home/statocles/.cpanm/work/1451801109.21713/Statocles-0.062/blib/lib/Statocles/Plugin/High
light.pm line 8.
BEGIN failed--compilation aborted at /home/statocles/.cpanm/work/1451801109.21713/Statocles-0.062/blib/lib/Statocles/Plugin/Highlight.pm line 10.
Compilation failed in require at /usr/share/perl5/Module/Runtime.pm line 317.
    # Child (unknown command specified) exited without calling finalize()

#   Failed test 'unknown command specified'
#   at /home/statocles/perl5/lib/perl5/Test/Builder.pm line 279.
```

Please skip this test when module not found (it mentioned in 'recommends:').

**Comment by preaction** [comment]
Sorry about that. I'm going to write a test that ensures I don't forget this again, then I'll cut a new release so it's installable again...

**Comment by preaction** [comment]
I'm going to try to make the travis-perl helpers do this, since I can't find a good way to do it locally and automatically (see travis-perl/helpers#27)

**Comment by preaction** [comment]
I've committed a new thing for travis to properly test this, but it relies on me keeping it updated, which is how this mess keeps happening, so it's a temporary measure at best. I clearly still haven't fixed this, and will need to make a new release tomorrow.
