### ISSUE TITLE
individual article is synhi'd, all indexes containing article are not.

### ISSUE THREAD

**Issue by kentfredric** [preaction/Statocles#429]
Presently:

> http://kentfredric.github.io/blog/2016/01/02/re-the-perl-jam-2-hashes-are-insecure/
Renders its html with code examples highlighted.

But
 > http://kentfredric.github.io/

Does not.

Of these, only the first includes this statement in its source

```html
<link href="/theme/plugin/highlight/default.css" rel="stylesheet" type="text/css">
```

**Comment by preaction** [comment]
List pages should probably combine the stylesheets/scripts from all their constituents. That should clear this up, but we want to make sure we're not pulling in a stylesheet/script unnecessarily, so we need to make sure we're only processing the section that's being shown.
