### ISSUE TITLE
`%= highlight TYPE => begin` leaves extra leading padding

### ISSUE THREAD

**Issue by kentfredric** [preaction/Statocles#431]
the syntax
```
%=highlight Perl => begin
use strict;
use warnings;
% end
```

Renders the same as if I'd done

```
%=highlight Perl => "\nuse strict;\nuse warnings;\n"
```

That is, it injects additional whitespace between "use strict" and the top of the box, which was something that didn't happen when I did 
```
%=code highlight Perl => begin
```

Where `code` was implemented as

```perl 
  return "<pre><code>$_[2]</code></pre>"
```

Though I guess the problem is related to the removal of this:
```diff
     if ( ref $text eq 'CODE' ) {
         $text = $text->();
-        # This adds an extra newline to the first line, so remove it
-        $text =~ s/^\n//;
     }
```

**Comment by preaction** [comment]
Oops. Yeah. When I was halfway through trying to guess if I needed to wrap a `<pre>`, I removed that because I dealt with it elsewhere. Then when I found I couldn't guess, I didn't put it back...
