### ISSUE TITLE
create.t fails often

### ISSUE THREAD

**Issue by andk** [preaction/Statocles#480]
I see many fails from my smokers and wanted to help but could not reproduce any of the fails yet.

But I find this suspicious:

main::(t/command/create.t:4):   my $SHARE_DIR = path( __DIR__, '..', 'share' );

It seems to me it might happen that two conflicting states of two different perls try to do something in this share/ directory. What do you think?

**Comment by preaction** [comment]
They should all only be reading from that directory, never writing. The content in the default site comes from the main `share/` dir, that line is the `t/share/` dir.

It could be #474: Depending on the current time and time zone of the machine, it may be "yesterday" in UTC, so when the site is created, the initial blog post is today, but the site builds itself for yesterday, and then doesn't show the blog post, which makes that specific test fail.

For posterity, here's one of the reports: http://www.cpantesters.org/cpan/report/5400add4-ebce-11e5-ba13-4eb3864cb8f0

**Comment by andk** [comment]
Yes, I'm in UTC+1 right now and at midnight the test started failing and at 1:00 it started passing again.

**Comment by preaction** [comment]
Alright. I've got a fix to #474 in and I'll push a release tonight to fix this. Thanks for the report!
