### ISSUE TITLE
Do not allow blog slugs to start/end with a "-"

### ISSUE THREAD

**Issue by preaction** [preaction/Statocles#507]
If a blog title starts or ends with an unsafe URL character, we should simply remove it, not replace it with a `-` like other characters. Having a `-` at the beginning or end of the URL looks strange.

For example, "How do I X?" gets turned into the slug `how-do-i-x-`. The trailing `-` looks strange and useless hanging there.

**Comment by ferki** [comment]
I plan to send a PR for this soon.
