### ISSUE TITLE
On creating site, Statocles tries to log before log object exists

### ISSUE THREAD

**Issue by wbazant** [preaction/Statocles#563]
This was an obstacle when I wanted to try out the project, this is a report and a patch I did to push the project on.

I'm creating a site. Stuff breaks with this error:
```
Can't call method "log" on an undefined value at lib/Statocles.pm line 171, <STDIN> line 4.
```
This was the stack trace when I ran it under debugger:
```
@ = DB::DB called from file 'lib/Statocles.pm' line 171
$ = site::log('site') called from file 'lib/Statocles/Command/bundle.pm' line 48
. = Statocles::Command::bundle::bundle_theme('Statocles::Command::bundle', 'default', 'theme') called from file 'lib/Statocles/Command/create.pm' line 129
$ = Statocles::Command::create::create_site(ref(Statocles::Command::create), ref(ARRAY)) called from file 'lib/Statocles/Command/create.pm' line 12
$ = Statocles::Command::create::run(ref(Statocles::Command::create), 'test-site') called from file 'lib/Statocles.pm' line 76
$ = Statocles::run('Statocles', 'create', 'test-site') called from file 'bin/statocles' line 18
```

I see lib/Statocles/Site.pm does this in BUILD:
```
$Statocles::SITE = $self;
```

I also see that Statocless::Command wire up an object `site` of that class, but as far as I can tell this doesn't happen for me. I don't know if it's a bug or if I haven't installed it right. I ran this with Perl 5.18, and I see the Travis build is failing for it currently (I had the same failing test, and installed with -f), so maybe it's connected somehow.

I've patched it for myself in Statocles.pm as follows:
```
our $SITE;

BEGIN {
    package # Hide from PAUSE
        site;
    sub log {
        use Mojo::Log;
        our $log = Mojo::Log->new;
        return $log;
    }
}
```

**Comment by jjatria** [comment]
Any chance this will get addressed? It's been more than a year, and currently it means new users using the default options cannot create a site.
If this is blocked on some other major re-factor, maybe we could just temporarily comment-out the logging line so the `create` command is not broken.

**Comment by wbazant** [comment]
Doug is making a v2, see the other branch.

**Comment by preaction** [comment]
The current code in master is definitely broken. Since I'm working on the v2 branch, I just realized that I can release bugfixes from the old code before I started refactoring (I've pushed it as the 'v0' branch). I'll release a new version right now.
